language: csharp
solution: CompuMaster.Console

#before_install:
#  - nuget install NUnit.Runners -Version 3.10.0 -OutputDirectory testrunner

install:
  - nuget restore CompuMaster.Console

script:
  - msbuild /p:Configuration=Release /p:Platform="Any CPU" /p:PostBuildEvent="" CompuMaster.Console
#  - mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./CompuMaster.Test.xxxxx/bin/CompuMaster.Test.xxxxx.dll