name: Publish/Upload dotnet package on release

on:
  release:
    types: [created]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: CI_CD

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

    publish:
        runs-on: ubuntu-latest
        #if: false # always skip job

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 5.0.x

            - name: Install dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration=${{env.BUILD_CONFIGURATION}} --no-restore

            - name: Pack
              run: dotnet pack --no-build --configuration=${{env.BUILD_CONFIGURATION}} Console/CompuMaster.Console.vbproj --output .

            - name: PushNuget
              run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
              #run: dotnet nuget push <my project>/bin/Release/*.nupkg

            - name: Publish Package Artifacts
              uses: actions/upload-artifact@v2
              with:
                name: Nupkg Artifacts
                path: ./**/*.nupkg
